spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://minical-rds-instance.crtoajixjdqa.ap-northeast-2.rds.amazonaws.com/minical_rds
    username: admin
    password: mini5737