version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/github_action
    overwrite: yes
    owner: root
    group: root
    mode: '0755'
    
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: ubuntu
    mode: '0755'

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 10000
      runas: root
 
